// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LogisticCalculationMVC.Models
{
    public partial class Workplace
    {
        public Workplace()
        {
            Employees = new HashSet<Employee>();
        }

        public int Id { get; set; }
        public string WorkplaceName { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int Psc { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
    }
}